import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'react-bootstrap';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Paste Bucket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Paste Bucket</h1>
      <p>
        This is an application for people to upload share various snippets of
        text.
      </p>
      <Button href="/create-snippet" variant="outline-info">
        Create a Snippet
      </Button>
    </div>
  );
}
